feat(transactions): send_7702_tx
alloy-rs/examples pull request #129
Opened 2024-08-16 04:56 UTC by yash-atreya

## Motivation

#128 

## Solution

send 7702 tx. Need latest anvil.

## PR Checklist

- [ ] Added Documentation
- [ ] Breaking changes

2024-08-16 18:37 UTC, mattsse requested changes
pedantic nit, can merge after new alloy release

2024-08-16 18:37 UTC, mattsse commented on examples/transactions/examples/send_eip7702_transaction.rs
> +    assert!(receipt.inner.logs().len() == 1);
can use assert_eq!

2024-08-16 18:37 UTC, mattsse commented on examples/transactions/examples/send_eip7702_transaction.rs
> +    assert!(receipt.inner.logs()[0].address() == authority.address());
same

2024-08-16 22:39 UTC, zerosnacks approved these changes
PR lgtm, I don't think we would want to merge this into main with the patch and instead wait for the next Alloy release?

2024-08-16 22:43 UTC, zerosnacks commented on Cargo.toml
> +alloy = { git = "https://github.com/alloy-rs/alloy", rev = "f5eaddf" }
TODO: remove

2024-08-16 22:47 UTC, onbjerg approved these changes

2024-08-16 22:54 UTC, DaniPopes commented on examples/transactions/examples/send_eip7702_transaction.rs
> +    #[sol(rpc, bytecode = "6080604052348015600f57600080fd5b5060d980601d6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80637b3ab2d01460375780639ee1a44014603f575b600080fd5b60
can you add the command you used to compile this

2024-08-21 04:43 UTC, yash-atreya commented
Awaiting new alloy release before merging

2024-08-29 11:17 UTC, onbjerg commented
@yash-atreya alloy 0.3.0 is released, so this should be unblocked

2024-08-29 12:03 UTC, merged