feat(`advanced`): foundry-fork-db
alloy-rs/examples pull request #145
Opened 2024-09-25 12:02 UTC by yash-atreya

## Motivation

The fork-db functionality was extracted from foundry as `foundry-fork-db`. This is a generic tool to create and manage forks. 

foundry's current forking mechanism and management of multiple forks is based on this. 

## Solution

Demonstrate a minimal example of how this works using `SharedBackend` and `BlockchainDb`. 

## PR Checklist

- [ ] Added Documentation
- [ ] Breaking changes

2024-09-25 14:33 UTC, mattsse requested changes
cool, this should also demonstrate how to use it with revm, like using the Database API and transacting a transfer for example

2024-09-25 14:33 UTC, mattsse commented on examples/advanced/examples/foundry_fork_db.rs
> +    };
we should make creating BlockchainDbMeta easier with a helper function that accepts `Block`

tracking

2024-09-27 12:39 UTC, klkvr approved these changes
nice, lgtm!

I think we should also eventually demonstrate how foundry-fork-db can be plugged into `Provider`'s `call` and `estimate_gas` fns to leverage local EVM simulation and caching of individual storage slots

2024-09-27 14:22 UTC, yash-atreya commented
@mattsse can we have a new fork-db release and merge this?

2024-10-01 15:18 UTC, zerosnacks commented on examples/advanced/examples/foundry_fork_db.rs
> +    let mut evm = configure_evm_env(block, shared.clone(), configure_tx_env(tx_req));
Let's say this fork environment is configured / updated on every block update, how would that look like? I think this is a common scenario.

2024-10-01 15:31 UTC, zerosnacks approved these changes

2024-10-01 15:49 UTC, mattsse approved these changes
cool

2024-10-01 15:49 UTC, merged